name: code-server # Will be used for network auto naming and image names
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    pull_policy: always
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Ljubljana
      # - PASSWORD=password #optional
      # - HASHED_PASSWORD= #optional
      # - SUDO_PASSWORD=password #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/mnt/svgo #optional
    volumes:
      - "/mnt/Development/GitRepos/.code-server-configs:/config" # Volume mapping for persistency
      - "/mnt/Development/GitRepos:/mnt" # Volume mapping for persistency
    ports:
      - 8443:8443
volumes:
  data: # It will prepend the project name