name: Local Assistant
version: 1.0.0
schema: v1
models:
  # - name: qwen3:4b
  #   provider: ollama
  #   model: qwen3:4b
  #   apiBase: http://ollama.lan:11434
  #   roles:
  #     - chat
  - name: qwen2.5-coder:1.5b
    provider: ollama
    model: qwen2.5-coder:1.5b
    apiBase: http://ollama.lan:11434
    roles:
      - autocomplete
  # - name: Nomic Embed
  #   provider: ollama
  #   model: nomic-embed-text:latest
  #   roles:
  #     - embed
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
